
[colors]
# draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MonaspiceKR NF"
#family = "Monoid Nerd Font"
# family = "Monoid Nerd Font Mono"
# family = "Iosevka Nerd Font "
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
title = "Alacritty"
decorations = "none"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true

# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
